
function ast_to_asm_program(program :: Program)
    asm = "this is an assembly code generated by minc compiler ...\n"
    throw(ErrorException("YOU MUST IMPLEMENT jl/minc/minc_cogen.jl:ast_to_asm_program"))
    asm
end
