package main
func ast_to_asm_program(program * Program) string {
	asm := "this is an assembly code generated by minc compiler ...\n"
	panic("YOU MUST IMPLEMENT go/minc/minc_cogen.go:ast_to_asm_program")
	return asm
}
