""" md
#* Programming Language (1) --- Basics
"""

""" md w

Enter your name and student ID.

 * Name:
 * Student ID:

"""

""" md
# Roadmap

* In this notebook, you will learn most basic elements of the four languages that are in the main scope of this course, Go, Julia, OCaml, and Rust
* For this exercise, you are encouraged to work on <font color=blue>TWO languages --- one from Julia or OCaml, and another from Go or Rust</font> --- but you can start with one if it sounds overwhelming to you (you can work on another later)
* These basic elements are found and common in virtually all programming languages
* Specifically, you will learn the following topics and solve a few coding problems
  * **minimum** : Writing a minimum program and compiling/running it
  * **function** : Defining a function
  * **variables** : Introducing variables
  * **conditional** : Conditional expressions/statements (if, match, etc.)
  * **iteration** : Iterations (for, while, etc.)
* Your goal in this notebook is to solve at least <font color=blue>TWO</font> problems from the last topic <font color=blue>(Iterations)</font>

"""

""" md
# How to learn with this notebook

* The best way to master a new programming language highly depends on prior knowledge and experiences you already have about programming in general and/or a particular programming language you try to master this time
* For example, if you have a relatively short experience in programming, the best way to learn would be to start from the simplest topic and move toward gradually more advanced ones, tackling one or more problem instances on each topic
* On the other hand, if you already have learned several programming languages, you would already know common elements in many programming languages (functions, variables, loops, etc.); the best way to learn would be to focus on main differences between them with moderately complex examples from the beginning
* Thus, rather than having everybody solve exactly the same set of problems in the same order, this notebook generates problems _on demand_, according to your preference
* Note: it's not that problems are generated by AI on the fly; a stock of problems has been generated, from which you can choose the next problem you work on in any way you like
* This notebook also equips with AI tutor you can ask help and/or feedback

"""

""" md
# AI tutor

* In this course, each notebook is extended with an AI tutor
* Execute the following to enable it
* For AI use policy in this course, see [home page](https://taura.github.io/programming-languages/index.html#ai_policy)

"""

""" code w kernel=python """
import heytutor
""" """

""" md
# Show status

* `show_status` function shows which problems are available for each topic
* the top level list is the list of topics; the sub-list under a topic is the list of problems on the topic
* problems you've already generated are shown as links; click them to open the notebooks (or you can open them from the side menu)
"""

""" code """
TOPICS = ["minimum", "fundef", "variables", "conditional"]
heytutor.show_status(topics=TOPICS)
""" """

""" md
# Generate a problem

* `gen_problem` function generates a problem based on your preference
* Uncommenting one of the following preferences and execute the cell below
* It will create a directory in `problems/{topic}/{problem}` and put a notebook and four subdirectories, one for each language (`go, jl, ml,` and `rs`)
* Click on the link to the notebook just created and work on it

* You may be able to guess what each preference means by its name, but to clarify
  * `next_topic`
    * get a problem from the "next" topic, which is the topic next to the last one (in the above list) from which at least one problem has been fetched
    * useful when you start from basic topics toward advanced ones, have done a problem on a topic, and want to go to the next topic
  * `last_topic`
    * get a problem from the "last" topic, which is the last topic (in the above list) from which at least one problem has been fetched
    * useful when you started from the most basic topic, have done a problem on a topic, and repeat the same topic
  * `prev_topic`
    * get a problem from the "previous" topic, which is the topic previous to the first topic from which at least one problem has been fetched
    * useful when you started from advanced topics, found a topic too advanced for now, and want to work on a slightly more basic problem
  * `first_topic`
    * get a problem from the "first" topic, which is the first topic from which at least one problem has been fetched
    * useful when you started from advanced topics, have done a problem on the topic, and repeat the same topic
  * `random` : get a random problem that has not been fetched
  * `match:REGEX` : get a problem matching REGEXP.  A problem P from a topic T is represented as T/P, so for example, `match:function/.*` matches any problem of topic "function", whereas `match:.*/xyz` matches any problem named `xyz`, from any topic

"""

""" code """
PREFERENCE = "next_topic"
#PREFERENCE = "last_topic"
#PREFERENCE = "prev_topic"
#PREFERENCE = "first_topic"
#PREFERENCE = "random"
#PREFERENCE = "match:conditional/.*"
#PREFERENCE = "match:.*/leap_year"

heytutor.gen_problem(topics=TOPICS, pref=PREFERENCE)
""" """

""" md
# How to Use AI tutor
"""

""" md
## `%%hey`

* By executing a cell beginning with `%%hey` you can ask a question to AI
"""

""" codex w
%%hey

How to write a function in C++?
"""

""" md

* `%%hey` can be followed by `problem_file=...` and `answer_file=...`
* `{{problem}}` in the cell is automatically replaced by the contents of the file specified with `problem_file=`
* `{{answer}}` in the cell is automatically replaced by the contents of the file specified with `answer_file=`
* For example,
* A hint on this specific problem
```
%%hey problem_file=hello.md
I am working on Rust. Give me a hint on this problem.
{{problem}}
```
* In each problem notebook, `{{problem}}` is actually in the system prompt, so you can omit it.  But if you are unsure, it is safe to make it explicit
```
%%hey problem_file=hello.md
I am working on Rust. Give me a hint on this problem.
```
* Help when you struggle
```
%%hey problem_file=hello.md answer_file=rs/hello.rs
I get this error when I compile it. What's wrong?"

My program:
{{answer}}

Error message:
  <paste the compile error message> 

```
* You are encouraged to ask a feedback once you think you are done with the problem, to know if there is a better answer.  You can do so by something like:
```
%%hey problem_file=hello.md answer_file=rs/hello.rs
My Answer:
{{answer}}

Give me a feedback to my answer.
```
"""

""" md
## `%%bash_` and `%%writefile_`

* There are `%%bash_` and `%%writefile_` that are similar to `%%bash` and `%%writefile`, respectively, but extended to work with AI tutor
* Problem notebooks have many such cells to help you execute commands quickly
"""

""" codex w
%%writefile_ hello.c
/* a Python cell that just saves the contents into a file (hello.c) */
#include <stdio.h>
int main() {
    printf("hello\n");
    return 0;
}
"""

""" codex w kernel=python
%%bash_
gcc hello.c -o hello
./hello
"""

""" md

## Two ways to edit and execute programs

* You can either edit your program in Jupyter cells (with `%%writefile_`) and save it by executing it, or directly edit files by your favorite editor
* Similarly, you can compile and run your program using Jupyter cells (with `%%bash_`), Jupyter or SSH terminals, or in your IDE (e.g., VScode)

* If you edit your programs outside Jupyter, be extra careful not to lose your work by accidentally executing `%%writefile_` cells with old contents
* Also, to make sure your output is conforming to the expectation, you are encouraged to eventually reflect your work in the Jupyter notebook, by copying the file content into the corresponding `%%writefile_` cell and running `%%bash_` cells to compile and run it
* In addition, when you ask AI for help, you are encouraged to use AI in the provided notebook rather than external ones, as it records your interaction with AI for analysis

"""

