#
# compile
#
#mk_nb_flags := --dbg 2

nb_srcs :=
nb_srcs += $(wildcard nb/source/pl06_*/*.sos)

aux_srcs :=
#aux_srcs += $(wildcard nb/source/pl04_*/00hello/??/hello.??)
#aux_srcs += $(wildcard nb/source/pl04_*/01build_sys/??/_)
#aux_srcs += $(wildcard nb/source/pl04_*/p?/??/_)
#aux_srcs += $(wildcard nb/source/*/img/*.png)
#aux_srcs += $(wildcard nb/source/*/img/*.svg)
#aux_srcs += $(wildcard nb/source/*/misc/*.html)

ans_aux_srcs :=
#ans_aux_srcs += $(wildcard nb/source/pl04_*/01build_sys/??/foo)
#ans_aux_srcs += $(wildcard nb/source/pl04_*/p?/??/*/*/*)
#ans_aux_srcs += $(wildcard nb/source/pl04_*/p?/??/*/*.*)
#ans_aux_srcs += $(wildcard nb/source/pl04_*/p?/??/*/*-*)

users_csv := users.csv

feedback_class := os
include ../../../jupyter_tools/authoring/jupyter_tools.mk
